services:
  rag-app:
    build: .
    image: paper-rag-app
    container_name: paper-rag
    ports:
      - "8501:8501"
    volumes:
      - ./src:/app/src
      - ./app.py:/app/app.py
      - ./data:/app/data
      - ./chroma_db:/app/chroma_db
    env_file:
      - .env
    stdin_open: true
    tty: true
